version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8010"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
    networks:
      - mynetwork
    env_file:
      - .env

  db:
    image: postgres
    environment:
      POSTGRES_DB: positivegroup
      POSTGRES_USER: positive_admin
      POSTGRES_PASSWORD: positive19062024reg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:8010"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: {}