# Generated by Django 5.0.6 on 2024-06-28 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positive', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='second_phone',
        ),
    ]
