# Generated by Django 5.0.6 on 2024-06-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positive', '0004_remove_customuser_second_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
