# Generated by Django 5.0.6 on 2024-06-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positive', '0005_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='', max_length=1, verbose_name='last name'),
        ),
    ]
