# Generated by Django 5.0.6 on 2024-07-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positive', '0008_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
