# Generated by Django 5.0.6 on 2024-07-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positive', '0009_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_account',
            field=models.CharField(choices=[('Basico', 'Basico'), ('Premium', 'Premium'), ('Master', 'Master')], default='Basico', max_length=7),
        ),
    ]
