# Generated by Django 5.0.6 on 2024-07-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positive', '0010_alter_customuser_type_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_account',
            field=models.CharField(choices=[('Free', 'Free'), ('Basico', 'Basico'), ('Premium', 'Premium'), ('Master', 'Master')], default='Free', max_length=7),
        ),
    ]
