# Generated by Django 5.0.6 on 2024-09-21 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positive', '0012_customuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='albummeeting',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentcourse',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebook',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagealbummeeting',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planner',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocourse',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videomeeting',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='cover',
            field=models.ImageField(default='', upload_to='cover_ebook/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ebook',
            name='file',
            field=models.FileField(upload_to='file_ebook/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='imagealbummeeting',
            name='picture',
            field=models.ImageField(upload_to='album_meetings/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='picture',
            field=models.ImageField(upload_to='meeting/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(upload_to='news/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='planner',
            name='cover',
            field=models.ImageField(default='', upload_to='cover_planner/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planner',
            name='file',
            field=models.FileField(upload_to='file_planner/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='videocourse',
            name='video',
            field=models.FileField(upload_to='video_course/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='videomeeting',
            name='video',
            field=models.FileField(upload_to='video_meeting/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='cover',
            field=models.FileField(upload_to='cover_welcome/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='video',
            field=models.FileField(upload_to='video_welcome/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
